#debug: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] %msg%n"
  level:
#    root: DEBUG
    demo: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.cloud.config.server.environment.JdbcEnvironmentRepository: TRACE


server:
  port: 8888


spring:
  application:
    name: config-server-sandbox

  profiles:
    active: composite

  cloud:
    config:
      server:
        composite:
          - type: jdbc
            sql: "SELECT prop_key, prop_value FROM common.server_config WHERE application = ? AND profile = ? AND label = ?"
            default-label: main # label = 'main' will be used automatically
            order: 1 # 1 has higher order than 2
          - type: git
            uri: https://github.com/StevenSquallZou/config-sandbox # the repo which contains configuration files
            search-paths:
              - '{application}' # {application} = Client's spring.application.name
              - redis # other sub dir
              - datasource
            clone-on-start: true
            default-label: main # git branch to use
            force-pull: true # Forces fresh clone on startup
            basedir: file:///${user.home}/config-repo # Explicit cache location
            order: 2

  datasource:
    url: ${BASE_JDBC_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


encrypt:
  key: ${CONFIG_ENCRYPT_KEY} # from environment variable
  enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,git
  endpoint:
    health:
      show-details: always
    git:
      enabled: true