apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-sandbox-repo-hostpath-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/config-sandbox
    type: DirectoryOrCreate