apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-sandbox-repo-pvc
spec:
  storageClassName: config-sandbox-repo-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi