apiVersion: v1
kind: Secret

metadata:
  name: {{ include "config-server-chart.fullname" . }}-secret

type: Opaque
data:
  APP_DB_PASSWORD: {{ .Values.config.jdbc.passwords.app }}
  WORLD_DB_PASSWORD: {{ .Values.config.jdbc.passwords.world }}
  SAKILA_DB_PASSWORD: {{ .Values.config.jdbc.passwords.sakila }}
  REDIS_PASSWORD: {{ .Values.config.redis.password }}
